# Generated by Django 5.1.6 on 2025-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
        migrations.AddField(
            model_name='reader',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='reader_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='reader_permissions', to='auth.permission'),
        ),
    ]
